print("--------------- Exercise 3-4 --------------")
guests=["Jim Henson","Sarah Millican","Graham Norton"]
print("Dear", guests[0], "You are invited to dinner at my house. Please bring a friend.")
print("Dear", guests[1], "You are invited to dinner at my house. Please bring some jokes.")
print("Dear", guests[2], "You are invited to dinner at my house. Please bring a notecards and popcorn.")
print("--------------- Exercise 3-5 --------------")
print("Guest", guests[1], "can't make it for dinner.")
del guests[1]
guests.append("Marie Antoinette")
print("Dear", guests[0], "You are invited to dinner at my house. Please bring a friend.")
print("Dear", guests[1], "You are invited to dinner at my house. Please bring a notecards and popcorn.")
print("Dear", guests[2], "You are invited to dinner at my house. Please bring a cake.")
print("--------------- Exercise 3-6 --------------")
print("We can invite more guests now!")
guests.insert(0,"Jane Austen")
print(guests[0], "added to guest list")
guests.insert(2,"Anne of Green Gables")
print(guests[2], "added to guest list")
guests.append("Brent Spinner")
print(guests[5], "added to guest list")
count=len(guests)
print("Guests list has",count,"people!")
print("Dear", guests[0], "You are invited to dinner at my house. Please bring some stories.")
print("Dear", guests[1], "You are invited to dinner at my house. Please bring a friend.")
print("Dear", guests[2], "You are invited to dinner at my house. I know you aren't real but lets pretend.")
print("Dear", guests[3], "You are invited to dinner at my house. Please bring a notecards and popcorn.")
print("Dear", guests[4], "You are invited to dinner at my house. Please bring a cake.")
print("Dear", guests[5], "You are invited to dinner at my house. It's going to be interesting.")
print("--------------- Exercise 3-7 --------------")
print("Nevermind, we can't actually invite as many people as I thought.")
print("I can only invite 2 guests.")

print("Dear", guests[-1], "You are un-invited to dinner at my house. Don't call us. We'll call you")
guests.pop()
print("Dear", guests[-1], "You are un-invited to dinner at my house. Don't call us. We'll call you")
guests.pop()
print("Dear", guests[-1], "You are un-invited to dinner at my house. Don't call us. We'll call you")
guests.pop()
print("Dear", guests[-1], "You are un-invited to dinner at my house. Don't call us. We'll call you")
guests.pop()
print("Dear", guests[0], "You are invited to dinner at my house. Please bring some stories.")
print("Dear", guests[1], "You are invited to dinner at my house. Please bring a friend.")
del guests[-1]
del guests[-1]
print("Guest List:",guests)

